spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
jwt:
  key: localTestGood1234123412341234123412341234123412341234123412341234123412341234        # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 420
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com, test@gmail.com

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
